trigger:
  branches:
    include:
    - master
    - staging
    - refs/tags/*

pool:
  name: 'On-Prem Default'

variables:
  - group: Monitoring
  - name: sendEmail
    value: false

jobs:
  - job: 'DB'
    timeoutInMinutes: '0'
    steps:      
    - task: PowerShell@2
      displayName: 'Execute SQL Script'
      inputs:
        targetType: filePath
        filePath: 'ExecuteSQLScripts.ps1'
        arguments: '
          -serverInstance "fortress-sql-uat.database.windows.net"
          -database "fortress-uat"
          -username $(username_uat)
          -password $(password_uat)
          -sourceFolder "$(System.DefaultWorkingDirectory)\SQLScripts"
          -destFolder "$(Build.ArtifactStagingDirectory)"
          -stringToSearchFor $(string)
          '