trigger:
- master

pool:
  name: Non-Prod-Windows

steps:
- checkout: self

- task: Files-Validator@1
  inputs:
    rootDir: '$(Build.SourcesDirectory)'
    validateXML: true
    validateJSON: true
    validateYAML: true
    validatePS: true